/*
 *  Copyright (c) 2025 AVI-SPL, Inc. All Rights Reserved.
 */
package com.avispl.symphony.dal.avdevices.avcontrollers.planar.walldirector.types;

/**
 * Represents a set of supported commands.
 * Each constant in this enum corresponds to a specific command recognized by the system.
 *
 * @author Kevin / Symphony Dev Team<br>
 * @since 1.0.0
 */
public enum Command {
	NONE("NONE"),
	PANEL_LIST("PANEL.LIST"),
	PS_LIST("PS.LIST"),
	VC_LIST("VC.LIST"),
	ZONE_LIST("ZONE.LIST"),
	PRESET_LIST("PRESET.LIST"),
	WALL_PRODUCT("WALL.PRODUCT"),
	WALL_MODEL("WALL.MODEL"),
	MATRIX_COLUMNS("MATRIX.LAYOUT.COLUMNS"),
	MATRIX_ROWS("MATRIX.LAYOUT.ROWS"),
	BACKLIGHT_MODE("BACKLIGHT.MODE"),
	BACKLIGHT_INTENSITY("BACKLIGHT.INTENSITY"),
	WALL_HEIGHT("WALL.HEIGHT"),
	WALL_WIDTH("WALL.WIDTH"),
	STANDBY_MODE("STANDBY.MODE"),
	SYSTEM_POWER("SYSTEM.POWER"),
	SYSTEM_REBOOT("SYSTEM.REBOOT"),
	ID("ID"),
	MODEL_NAME("MODEL.NAME"),
	SERIAL_NUMBER("SERIAL.NUMBER"),
	TEMPERATURE("TEMPERATURE"),
	VOLTAGE("VOLTAGE"),
	FIRMWARE_VERSION("FIRMWARE.VERSION"),
	PANEL_RX_LENGTH("PANEL.RX.LENGTH"),
	PANEL_SIGNAL_QUALITY("PANEL.SIGNAL.QUALITY"),
	PANEL_POSITION("PANEL.POSITION"),
	COLOR_TEMP("COLOR.TEMP"),
	WHITE_BALANCE("WHITE.BALANCE"),
	GRAY_BALANCE_GAMMA("GRAY.BALANCE.GAMMA"),
	CONNECTION("CONNECTION"),
	PS_STATUS("PS.STATUS"),
	FAN_STATUS("FAN.STATUS"),
	INPUT_INFO("INPUT.INFO"),
	ZONE_INPUT("ZONE.INPUT"),
	ZONE_SOURCE("ZONE.SOURCE"),
	ZONE_ASPECT("ZONE.ASPECT"),
	ZONE_EXPECTED_SOURCE_HEIGHT("ZONE.EXPECTED.SOURCE.HEIGHT"),
	ZONE_EXPECTED_SOURCE_WIDTH("ZONE.EXPECTED.SOURCE.WIDTH"),
	ZONE_ORDER("ZONE.ORDER"),
	PRESET_ACTIVE("PRESET.ACTIVE"),
	PRESET_CURRENT("PRESET.CURRENT"),
	PRESET_NAME("PRESET.NAME"),
	PRESET_RECALL("PRESET.RECALL"),
	HOSTNAME("HOSTNAME"),
	NETWORK_DHCP("NETWORK.DHCP"),
	IPV4_ADDRESS("IPV4.ADDRESS"),
	IPV4_NETMASK("IPV4.NETMASK"),
	IPV4_GATEWAY("IPV4.GATEWAY"),
	NETWORK_DNS1("NETWORK.DNS1"),
	NETWORK_DNS2("NETWORK.DNS2"),
	NETWORK_MAC("NETWORK.MAC");

	private final String name;

	Command(String name) {
		this.name = name;
	}

	/**
	 * Retrieves {@link #name}
	 *
	 * @return value of {@link #name}
	 */
	public String getName() {
		return name;
	}
}
